name: Functional tests
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
    branches:
      - master
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        id: build
        run: |
          set +e
          mvn -B verify \
          -DskipUnitTests=true \
          -DskipModuleFunctionalTests=true \
          -Dtests.max-container-count=5 \
          -DdockerfileName=Dockerfile \
          --file extra/pom.xml | tee build_output.txt
          result=${PIPESTATUS[0]}
          echo "exit_code=$result" >> "$GITHUB_OUTPUT"

      - name: Upload full build output
        if: steps.build.outputs.exit_code != '0'
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build_output.txt

      - name: Read test failures into output
        id: test-results
        if: steps.build.outputs.exit_code != '0'
        run: |
          content=$(cat test_failures.txt)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Comment test failures on PR
        if: steps.build.outputs.exit_code != '0'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ **Functional tests CI Failed**
            
            ```
            ${{ steps.test-results.outputs.content }}
            ```
      - name: Fail if error is found in logs
        if: steps.build.outputs.exit_code != '0'
        run: exit 1
